language: "en"

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
  ranking_length: 5
  threshold: 0.3
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3    # Confidence threshold for fallback
  ambiguity_threshold: 0.1    # Handles uncertain cases
  fallback_action_name: "action_handle_out_of_scope"    # This should trigger the LLM

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3    # Confidence threshold for core fallback
  core_fallback_action_name: "action_handle_out_of_scope"
  enable_fallback_prediction: true
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250315-212153-progressive-indent
